id: P009258
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1287
  title: འཇིགས་བྱེད་ར་ལུགས་ཀྱི་སྒྲུབ་ཐབས་བདུད་འཇོམས་སྣང་བ
  author: ''
  volumes:
    b5e52da009744a6f9c65be506b759332:
      image_group_id: I1CZ1795
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
